import '@/styles/globals.css';
import { Manrope, Lexend_Deca } from 'next/font/google';
import { cn } from '@/utils/helpers/cn';

// Components
import Footer from '@/components/footer';
import Header from '@/components/header';
import Providers from '@/components/providers';

// TODO: Change font to Satoshi

const mainFont = Manrope({ subsets: ['latin'], variable: '--font-main' });
const logoFont = Lexend_Deca({ subsets: ['latin'], variable: '--font-logo' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en" className={cn(mainFont.variable, logoFont.variable)}>
      <body className="font-main">
        <Providers>
          <Header />

          <main>{children}</main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
